
# parsetab.py
# This file is automatically generated. Do not edit.
_tabversion = '3.5'

_lr_method = 'LALR'

_lr_signature = '9E6541B8B9E68717521FA8EBB5B47D54'
    
_lr_action_items = {'WORD':([1,3,5,6,8,10,11,12,14,15,17,],[-11,5,5,-6,5,-8,5,5,-9,-7,-10,]),'ASTERISK':([1,3,6,10,12,14,15,17,],[-11,8,-6,-8,8,-9,-7,-10,]),'EOL':([0,1,3,4,5,6,8,10,11,12,13,14,15,16,17,19,],[1,-11,1,1,1,-6,1,-8,1,1,1,-9,-7,-2,-10,-1,]),'COMMENT_END':([1,6,7,9,10,12,14,15,17,18,],[-11,-6,-3,16,-8,-4,-9,-7,-10,-5,]),'TAG':([1,3,5,6,8,10,11,12,14,15,17,],[-11,11,11,-6,11,-8,11,11,-9,-7,-10,]),'COMMENT_START':([0,1,4,],[3,-11,3,]),'$end':([1,2,16,19,],[-11,0,-2,-1,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'rest_of_line':([3,5,8,11,12,],[6,14,15,17,6,]),'pdcontent':([3,12,],[7,18,]),'pdbody':([3,],[9,]),'eol':([0,3,4,5,8,11,12,13,],[4,10,4,10,10,10,10,19,]),'pddoc':([0,4,],[2,13,]),'line':([3,12,],[12,12,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> pddoc","S'",1,None,None,None),
  ('pddoc -> eol pddoc eol','pddoc',3,'p_pddoc','ext_lexer.py',73),
  ('pddoc -> COMMENT_START pdbody COMMENT_END','pddoc',3,'p_pddoc','ext_lexer.py',74),
  ('pdbody -> pdcontent','pdbody',1,'p_pdbody','ext_lexer.py',86),
  ('pdcontent -> line','pdcontent',1,'p_pdcontent','ext_lexer.py',92),
  ('pdcontent -> line pdcontent','pdcontent',2,'p_pdcontent','ext_lexer.py',93),
  ('line -> rest_of_line','line',1,'p_line','ext_lexer.py',100),
  ('line -> ASTERISK rest_of_line','line',2,'p_line','ext_lexer.py',101),
  ('rest_of_line -> eol','rest_of_line',1,'p_rest_of_line','ext_lexer.py',107),
  ('rest_of_line -> WORD rest_of_line','rest_of_line',2,'p_rest_of_line','ext_lexer.py',108),
  ('rest_of_line -> TAG rest_of_line','rest_of_line',2,'p_rest_of_line','ext_lexer.py',109),
  ('eol -> EOL','eol',1,'p_eol','ext_lexer.py',130),
]
